from __future__ import annotations

import csv
import json
from pathlib import Path

from quino.domain.plotting import PlotDef
from quino.domain.workspace import Run


def export_run_json(run: Run, artifact: dict, out_path: Path) -> None:
    payload = {
        "run": {
            "id": run.id,
            "analysis_id": run.analysis_id,
            "created_at": run.created_at,
            "finished_at": run.finished_at,
            "status": run.status,
            "note": run.note,
            "metrics": dict(run.metrics),
            "warnings": list(run.warnings),
            "config_snapshot": dict(run.config_snapshot),
        },
        "artifact": artifact,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def export_run_csv(run: Run, artifact: dict, out_path: Path, *, mode: str = "wide") -> None:
    artifact_type = artifact.get("type")
    if artifact_type == "dynamic":
        _export_dynamic_csv(artifact, out_path, mode=mode)
        return
    if artifact_type == "kinematic":
        _export_kinematic_csv(artifact, out_path)
        return
    raise NotImplementedError(f"CSV export not implemented for type {artifact_type!r}")


def export_matplotlib_script(plot: PlotDef, artifact: dict, out_py: Path) -> None:
    out_py.parent.mkdir(parents=True, exist_ok=True)
    sidecar = out_py.with_suffix(".csv")
    headers = ["time", *[f"{series.sensor_id}_{series.channel}" for series in plot.y_series]]
    rows = []
    for index, time_value in enumerate(artifact.get("time", [])):
        row = [time_value]
        for series in plot.y_series:
            key = f"sensor:{series.sensor_id}:{series.channel}"
            frame = artifact.get("frames", [])[index] if index < len(artifact.get("frames", [])) else {}
            row.append(frame.get(key, ""))
        rows.append(row)
    with sidecar.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(headers)
        writer.writerows(rows)
    script = f'''"""Auto-generated by QUINO. Recreate the figure for plot {plot.title!r}."""
import csv
import matplotlib.pyplot as plt

times = []
series = {{name: [] for name in {headers[1:]!r}}}
with open(r"{sidecar.name}", encoding="utf-8") as stream:
    reader = csv.reader(stream)
    header = next(reader)
    for row in reader:
        times.append(float(row[0]))
        for idx, col in enumerate(header[1:]):
            series[col].append(float(row[idx + 1]))

fig, ax = plt.subplots()
for name, ys in series.items():
    ax.plot(times, ys, label=name)
ax.set_title({plot.title!r})
ax.legend()
ax.grid(True, alpha=0.3)
plt.show()
'''
    out_py.write_text(script, encoding="utf-8")


def _export_dynamic_csv(artifact: dict, out_path: Path, *, mode: str) -> None:
    times = artifact.get("time", [])
    frames = artifact.get("frames", [])
    keys: list[str] = []
    seen: set[str] = set()
    for frame in frames:
        for key in frame:
            if key.startswith("sensor:") and key not in seen:
                seen.add(key)
                keys.append(key)
    if mode == "wide":
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8", newline="") as stream:
            writer = csv.writer(stream)
            writer.writerow(["time", *keys])
            for time_value, frame in zip(times, frames):
                writer.writerow([time_value, *[frame.get(key, "") for key in keys]])
        return
    if mode == "per_sensor":
        out_path.mkdir(parents=True, exist_ok=True)
        by_sensor: dict[str, list[str]] = {}
        for key in keys:
            _prefix, sensor_id, _channel = key.split(":", 2)
            by_sensor.setdefault(sensor_id, []).append(key)
        for sensor_id, sensor_keys in by_sensor.items():
            channels = [key.split(":", 2)[2] for key in sensor_keys]
            with (out_path / f"{sensor_id}.csv").open("w", encoding="utf-8", newline="") as stream:
                writer = csv.writer(stream)
                writer.writerow(["time", *channels])
                for time_value, frame in zip(times, frames):
                    writer.writerow([time_value, *[frame.get(key, "") for key in sensor_keys]])
        return
    raise ValueError(f"Unknown mode {mode!r}")


def _export_kinematic_csv(artifact: dict, out_path: Path) -> None:
    from itertools import product

    axes = artifact.get("sweep_axes", [])
    shape = artifact.get("shape", [])
    sensors = artifact.get("sensors", {})
    out_path.mkdir(parents=True, exist_ok=True)
    idx_lists = [list(range(n)) for n in shape]
    for sensor_id, blob in sensors.items():
        channels = blob.get("channels", [])
        values = blob.get("values", [])
        stride = len(channels)
        with (out_path / f"{sensor_id}.csv").open("w", encoding="utf-8", newline="") as stream:
            writer = csv.writer(stream)
            writer.writerow([*[axis.get("label") or axis.get("id") for axis in axes], *[f"{sensor_id}_{ch}" for ch in channels]])
            for indices in product(*idx_lists):
                cell = 0
                step = 1
                for axis_idx in reversed(range(len(shape))):
                    cell += indices[axis_idx] * step
                    step *= shape[axis_idx]
                axis_values = [axes[i]["values"][indices[i]] for i in range(len(axes))]
                row_values = values[cell * stride:(cell + 1) * stride]
                writer.writerow([*axis_values, *row_values])
