# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_Plotter.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Plotter(object):
    def setupUi(self, widget_Plotter):
        widget_Plotter.setObjectName("widget_Plotter")
        widget_Plotter.resize(1201, 635)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_Plotter)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_main = QtWidgets.QSplitter(widget_Plotter)
        self.splitter_main.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_main.setOpaqueResize(True)
        self.splitter_main.setObjectName("splitter_main")
        self.widget_control = QtWidgets.QWidget(self.splitter_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_control.sizePolicy().hasHeightForWidth())
        self.widget_control.setSizePolicy(sizePolicy)
        self.widget_control.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_control.setBaseSize(QtCore.QSize(400, 0))
        self.widget_control.setObjectName("widget_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_control)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_control)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_import_matrix = QtWidgets.QToolButton(self.widget)
        self.toolButton_import_matrix.setObjectName("toolButton_import_matrix")
        self.horizontalLayout_2.addWidget(self.toolButton_import_matrix)
        self.toolButton_export = QtWidgets.QToolButton(self.widget)
        self.toolButton_export.setEnabled(False)
        self.toolButton_export.setObjectName("toolButton_export")
        self.horizontalLayout_2.addWidget(self.toolButton_export)
        self.toolButton_delete = QtWidgets.QToolButton(self.widget)
        self.toolButton_delete.setEnabled(False)
        self.toolButton_delete.setObjectName("toolButton_delete")
        self.horizontalLayout_2.addWidget(self.toolButton_delete)
        self.verticalLayout_3.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.splitter_2 = QtWidgets.QSplitter(self.widget_control)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setChildrenCollapsible(True)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_channels = QtWidgets.QWidget(self.splitter_2)
        self.widget_channels.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_channels.setObjectName("widget_channels")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_channels)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_channels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setBaseSize(QtCore.QSize(0, 0))
        self.treeWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.widget_channels_control = QtWidgets.QWidget(self.widget_channels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_channels_control.sizePolicy().hasHeightForWidth())
        self.widget_channels_control.setSizePolicy(sizePolicy)
        self.widget_channels_control.setObjectName("widget_channels_control")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_channels_control)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.widget_channels_control)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.widget_plot = QtWidgets.QWidget(self.splitter_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_plot.setBaseSize(QtCore.QSize(800, 0))
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout_plot = QtWidgets.QVBoxLayout(self.widget_plot)
        self.verticalLayout_plot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_plot.setObjectName("verticalLayout_plot")
        self.horizontalLayout.addWidget(self.splitter_main)

        self.retranslateUi(widget_Plotter)
        QtCore.QMetaObject.connectSlotsByName(widget_Plotter)

    def retranslateUi(self, widget_Plotter):
        _translate = QtCore.QCoreApplication.translate
        widget_Plotter.setWindowTitle(_translate("widget_Plotter", "Plotter"))
        self.toolButton_import_matrix.setText(_translate("widget_Plotter", "Import"))
        self.toolButton_export.setText(_translate("widget_Plotter", "Export"))
        self.toolButton_delete.setText(_translate("widget_Plotter", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Plotter = QtWidgets.QWidget()
    ui = Ui_widget_Plotter()
    ui.setupUi(widget_Plotter)
    widget_Plotter.show()
    sys.exit(app.exec_())

